# リファレンス: https://github.com/lowlighter/metrics/blob/master/action.yml

name: Metrics
on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: puchimilk
          repo: metries
          
          template: classic
          config_gemoji: yes # non-unicode emojiを使えるように
          config_timezone: Asia/Tokyo
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes # 実行速度向上

          base: header, activity, community, repositories, metadata
          repositories: 100
          repositories_batch: 25
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          repositories_skipped: puchimilk/puchimilk
          commits_authoring: octocat@github.com
