# リファレンス: https://github.com/lowlighter/metrics/blob/master/action.yml

name: Metrics
on:
  schedule: [{ cron: '30 0,12 * * *' }]
  workflow_dispatch:
  push: { branches: ['master'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: puchimilk
          template: classic
          config_gemoji: yes
          config_timezone: Asia/Tokyo
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          
          base: header, activity, community, repositories, metadata
          repositories_batch: 25
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          repositories_skipped: puchimilk/puchimilk
